### ISSUE TITLE
pip install FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by LukeLIN-web** [mesonbuild/meson-python#498]
I run 
```
pip3 install mesonpy
```

Output 
```
Collecting mesonpy
  Using cached MesonPy-0.0.1.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-0o3x3b9d/mesonpy_3fd0dc16801a4805af66479d061250f9/setup.py", line 4, in <module>
          with open('requirements.txt') as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dnicolodi** [comment]
The package names in `meson-python`.
