### ISSUE TITLE
Python 3.13: AttributeError: module 'importlib.resources' has no attribute 'path'

### ISSUE THREAD

**Issue by buhtz** [mesonbuild/meson-python#688]
I am not a meson user. I activate Python 3.13 on my TravisCI for the first time and got this error that IMHO is related to meson.

    AttributeError: module 'importlib.resources' has no attribute 'path'

Thanks in advance

```
Collecting dbus-python
  Downloading dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... [?25l- \ | / - \ | / done
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h  Preparing metadata (pyproject.toml) ... [?25l- \ | / - \ | error
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31mÃ—[0m [32mPreparing metadata [0m[1;32m([0m[32mpyproject.toml[0m[1;32m)[0m did not run successfully.
  [31mâ”‚[0m exit code: [1;36m2[0m
  [31mâ•°â”€>[0m [31m[170 lines of output][0m
  [31m   [0m + meson setup /tmp/pip-install-r6butdza/dbus-python_81d4c15343dd405c86af5c55a9cbe0f8 /tmp/pip-install-r6butdza/dbus-python_81d4c15343dd405c86af5c55a9cbe0f8/.mesonpy-m2zjnu4f -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-r6butdza/dbus-python_81d4c15343dd405c86af5c55a9cbe0f8/.mesonpy-m2zjnu4f/meson-python-native-file.ini
  [31m   [0m The Meson build system
  [31m   [0m Version: 1.5.2
  [31m   [0m Source dir: /tmp/pip-install-r6butdza/dbus-python_81d4c15343dd405c86af5c55a9cbe0f8
  [31m   [0m Build dir: /tmp/pip-install-r6butdza/dbus-python_81d4c15343dd405c86af5c55a9cbe0f8/.mesonpy-m2zjnu4f
  [31m   [0m Build type: native build
  [31m   [0m Project name: dbus-python
  [31m   [0m Project version: 1.3.2
  [31m   [0m C compiler for the host machine: ccache cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  [31m   [0m C linker for the host machine: cc ld.bfd 2.38
  [31m   [0m Host machine cpu family: x86_64
  [31m   [0m Host machine cpu: x86_64
  [31m   [0m Compiler for C supports arguments -fno-common: YES
  [31m   [0m Compiler for C supports arguments -Wno-missing-field-initializers: YES
  [31m   [0m Compiler for C supports arguments -Wno-declaration-after-statement: YES
  [31m   [0m Compiler for C supports arguments -Wno-inline: YES
  [31m   [0m Compiler for C supports arguments -Wno-redundant-decls: YES
  [31m   [0m Compiler for C supports arguments -Wno-switch-default: YES
  [31m   [0m Compiler for C supports arguments -Wno-write-strings: YES
  [31m   [0m Compiler for C supports arguments -Wcast-align: YES
  [31m   [0m Compiler for C supports arguments -Wdouble-promotion: YES
  [31m   [0m Compiler for C supports arguments -Wduplicated-cond: YES
  [31m   [0m Compiler for C supports arguments -Wfloat-equal: YES
  [31m   [0m Compiler for C supports arguments -Wformat-nonliteral: YES
  [31m   [0m Compiler for C supports arguments -Wformat-security: YES
  [31m   [0m Compiler for C supports arguments -Wformat=2: YES
  [31m   [0m Compiler for C supports arguments -Winit-self: YES
  [31m   [0m Compiler for C supports arguments -Wlogical-op: YES
  [31m   [0m Compiler for C supports arguments -Wmissing-declarations: YES
  [31m   [0m Compiler for C supports arguments -Wmissing-format-attribute: YES
  [31m   [0m Compiler for C supports arguments -Wmissing-include-dirs: YES
  [31m   [0m Compiler for C supports arguments -Wmissing-noreturn: YES
  [31m   [0m Compiler for C supports arguments -Wnull-dereference: YES
  [31m   [0m Compiler for C supports arguments -Wpacked: YES
  [31m   [0m Compiler for C supports arguments -Wpointer-arith: YES
  [31m   [0m Compiler for C supports arguments -Wshadow: YES
  [31m   [0m Compiler for C supports arguments -Wswitch-enum: YES
  [31m   [0m Compiler for C supports arguments -Wundef: YES
  [31m   [0m Compiler for C supports arguments -Wunused-but-set-variable: YES
  [31m   [0m Compiler for C supports arguments -Wjump-misses-init: YES
  [31m   [0m Compiler for C supports arguments -Wmissing-prototypes: YES
  [31m   [0m Compiler for C supports arguments -Wnested-externs: YES
  [31m   [0m Compiler for C supports arguments -Wold-style-definition: YES
  [31m   [0m Compiler for C supports arguments -Wpointer-sign: YES
  [31m   [0m Compiler for C supports arguments -Wstrict-prototypes: YES
  [31m   [0m Configuring _dbus-python-config.h using configuration
  [31m   [0m 
  [31m   [0m Executing subproject dbus-gmain
  [31m   [0m 
  [31m   [0m dbus-gmain| Project name: dbus-gmain
  [31m   [0m dbus-gmain| Project version: undefined
  [31m   [0m dbus-gmain| C compiler for the host machine: ccache cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  [31m   [0m dbus-gmain| C linker for the host machine: cc ld.bfd 2.38
  [31m   [0m dbus-gmain| Compiler for C supports arguments -fno-common: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wcast-align: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wdouble-promotion: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wduplicated-branches: YES
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wduplicated-cond: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wfloat-equal: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wformat-nonliteral: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wformat-security: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wformat=2: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Winit-self: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wlogical-op: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wmissing-declarations: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wmissing-format-attribute: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wmissing-include-dirs: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wmissing-noreturn: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wnull-dereference: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wpacked: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wpointer-arith: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wredundant-decls: YES
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wshadow: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wswitch-default: YES
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wswitch-enum: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wundef: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wunused-but-set-variable: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wwrite-strings: YES
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wdeclaration-after-statement: YES
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wjump-misses-init: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wmissing-prototypes: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wnested-externs: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wold-style-definition: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wpointer-sign: YES (cached)
  [31m   [0m dbus-gmain| Compiler for C supports arguments -Wstrict-prototypes: YES (cached)
  [31m   [0m dbus-gmain| Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
  [31m   [0m dbus-gmain| Run-time dependency dbus-1 found: YES 1.12.20
  [31m   [0m dbus-gmain| Run-time dependency glib-2.0 found: YES 2.72.4
  [31m   [0m dbus-gmain| Run-time dependency gthread-2.0 found: YES 2.72.4
  [31m   [0m dbus-gmain| Program dbus-run-session found: YES (/usr/bin/dbus-run-session)
  [31m   [0m dbus-gmain| Build targets in project: 1
  [31m   [0m dbus-gmain| Subproject dbus-gmain finished.
  [31m   [0m 
  [31m   [0m Traceback (most recent call last):
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/mesonmain.py", line 191, in run
  [31m   [0m     return options.run_func(options)
  [31m   [0m            ~~~~~~~~~~~~~~~~^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 364, in run
  [31m   [0m     app.generate()
  [31m   [0m     ~~~~~~~~~~~~^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 187, in generate
  [31m   [0m     return self._generate(env, capture, vslite_ctx)
  [31m   [0m            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 226, in _generate
  [31m   [0m     intr.run()
  [31m   [0m     ~~~~~~~~^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreter/interpreter.py", line 3032, in run
  [31m   [0m     super().run()
  [31m   [0m     ~~~~~~~~~~~^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
  [31m   [0m     self.evaluate_codeblock(self.ast, start=1)
  [31m   [0m     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
  [31m   [0m     raise e
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 187, in evaluate_codeblock
  [31m   [0m     self.evaluate_statement(cur)
  [31m   [0m     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 219, in evaluate_statement
  [31m   [0m     return self.evaluate_if(cur)
  [31m   [0m            ~~~~~~~~~~~~~~~~^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 309, in evaluate_if
  [31m   [0m     self.evaluate_codeblock(i.block)
  [31m   [0m     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
  [31m   [0m     raise e
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 187, in evaluate_codeblock
  [31m   [0m     self.evaluate_statement(cur)
  [31m   [0m     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 205, in evaluate_statement
  [31m   [0m     self.assignment(cur)
  [31m   [0m     ~~~~~~~~~~~~~~~^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 642, in assignment
  [31m   [0m     value = self.evaluate_statement(node.value)
  [31m   [0m             ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 207, in evaluate_statement
  [31m   [0m     return self.method_call(cur)
  [31m   [0m            ~~~~~~~~~~~~~~~~^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 557, in method_call
  [31m   [0m     res = obj.method_call(method_name, args, kwargs)
  [31m   [0m           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 858, in method_call
  [31m   [0m     ret = method(state, args, kwargs)
  [31m   [0m           ~~~~~~^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 98, in wrapped
  [31m   [0m     ret = f(*wrapped_args, **wrapped_kwargs)
  [31m   [0m           ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 250, in wrapper
  [31m   [0m     return f(*nargs, **wrapped_kwargs)
  [31m   [0m            ~^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 569, in wrapper
  [31m   [0m     return f(*wrapped_args, **wrapped_kwargs)
  [31m   [0m            ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 508, in find_installation
  [31m   [0m     python = self._find_installation_impl(state, display_name, name_or_path, required)
  [31m   [0m              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 464, in _find_installation_impl
  [31m   [0m     if python.sanity(state):
  [31m   [0m        ~~~~~~~~~~~~~^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 73, in sanity
  [31m   [0m     ret = super().sanity()
  [31m   [0m           ~~~~~~~~~~~~~~^^
  [31m   [0m   File "/tmp/pip-build-env-vze8vz2f/overlay/lib/python3.13/site-packages/mesonbuild/dependencies/python.py", line 120, in sanity
  [31m   [0m     with importlib.resources.path('mesonbuild.scripts', 'python_info.py') as f:
  [31m   [0m          ^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m AttributeError: module 'importlib.resources' has no attribute 'path'
  [31m   [0m 
  [31m   [0m ../meson.build:106:16: ERROR: Unhandled python exception
  [31m   [0m 
  [31m   [0m     This is a Meson bug and should be reported!
  [31m   [0m [31m[end of output][0m
```

**Comment by dnicolodi** [comment]
I don't know what is wrong with your CI setup, but something is broken in your Python installation:
```
$ python3.13
>>> import importlib.resources
>>> importlib.resources.path
<function path at 0x10f7bea20>
```

**Comment by eli-schwartz** [comment]
https://github.com/python/cpython/commit/9ceaee74db7da0e71042ab0b385d844e9f282adb

It was originally scheduled for removal in python 3.13

In 3.13a6, it was un-deprecated and re-added to the standard library and documented as "the functional API" instead of "the deprecated API".

So, you can only possibly get this error if your CI setup is using an alpha release of Python that has long been superseded. In other words, yes, something is broken with Travis. :)

**Comment by eli-schwartz** [comment]
Yeah, rather baffling...

I peeked around a bit and it looks like Travis builds their own cpython 3.13 from scratch, I think *manually*? :scream: There are other people complaining about how Travis is outdated by the length of multiple alpha/beta versions.
